version: "3.9"

services:
  bot:
    build: .
    container_name: job_aggregator_bot
    command: python main.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./jobs.db:/app/jobs.db
      - ./user_session.session:/app/user_session.session
      - ./data:/app/data
    networks:
      - bot_network

  worker:
    build: .
    container_name: job_aggregator_worker
    command: python worker.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./jobs.db:/app/jobs.db
      - ./user_session.session:/app/user_session.session
      - ./data:/app/data
    networks:
      - bot_network

  dashboard:
    build: .
    container_name: job_aggregator_dashboard
    command: python web_dashboard.py
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./jobs.db:/app/jobs.db
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
